version: '3.8'

services:
  api-gateway:
    container_name: auth_service 
    build: ./
    ports:
      - "8083:8083"
    networks:
      - global-network
    depends_on:
      - migrate

  migrate:
    image: migrate/migrate
    networks:
      - global-network
    volumes:
      - ./internal/db/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  
                "postgres://postgres:root@postgres_dock:5432/memory?sslmode=disable", 
                "up" ]
# Docker Networks
networks:
  global-network:
    external: true 
